django_map/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('', include('map.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

map/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index),
    path('contacts/', views.contacts, name='contacts'),
    path('faq/', views.faq, name='faq'),
    path('info/', views.info, name='info'),
    path('terms_of_use/', views.ternms_of_use, name='terms_of_use'),
    path('my_tags/', views.my_tags, name='my_tags'),
    path('admin_tags/', views.admin_tags, name='admin_tags'),
    path(
        'admin_tags/<slug:action>/<int:tag_id>/',
        views.admin_tags,
        name='admin_tags'
    ),
]

map/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


class UnverifiedTag(models.Model):

    def images_directory_path(instance, filename):
        return '/'.join(['images', str(uuid.uuid4().hex + ".png")])

    name = models.CharField('Название', max_length=30)
    description = models.TextField('Описание', max_length=100)
    image = models.FileField('Изображение', upload_to=images_directory_path,
                             default="no pic", blank=True)
    location = models.CharField('Местоположение', max_length=30)
    x_coord = models.FloatField('Координата X')
    y_coord = models.FloatField('Координата Y')
    username = models.CharField('Имя пользователя', max_length=30)
    email = models.EmailField('Email', max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Метка(*)'
        verbose_name_plural = 'Метки(*)'


class Tag(models.Model):

    def images_directory_path(instance, filename):
        return '/'.join(['images', str(uuid.uuid4().hex + ".png")])

    name = models.CharField('Название', max_length=30)
    description = models.TextField('Описание', max_length=100)
    image = models.ImageField('Изображение', upload_to=images_directory_path,
                              default="no pic")
    location = models.CharField('Местоположение', max_length=30)
    x_coord = models.FloatField('Координата X')
    y_coord = models.FloatField('Координата Y')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Метка'
        verbose_name_plural = 'Метки'

templates/include/forms/add_unverified_tag.html
<div style="margin-top: 5%; margin-left: 5%">
    <h3 style="color: #fff">Добавить метку</h3>

    <form method="post" enctype="multipart/form-data" class="post-form" style="margin-top: 10%">
        {% csrf_token %}
        {{ form2.name }}<br>
        {{ form2.description }}<br>
        {{ form2.image }}<br>
        {{ form2.location }}<br>
        {{ form2.x_coord }}<br>
        {{ form2.y_coord }}<br>
        {{ form2.username }}<br>
        {{ form2.email }}<br>
        <button type="submit" name="btnform2" class="btn btn-primary" style="margin-top: 5%">Добавить</button>
    </form>
</div>

templates/include/forms/add_verified_tag.html
<<<<<<< Updated upstream
<form method="post" class="note-form" enctype="multipart/form-data">{% csrf_token %}
  <div class="form-group">
    <label for="note-title">1</label>
    <input type="text" name="title" class="form-control" id="note-title" placeholder="Enter Title" required>
  </div>
  <div class="form-group">
    <label for="note-description">2</label>
    <textarea type="text" name="text" class="form-control" id="note-description" placeholder="Description here"></textarea>
  </div>
    <div class="form-group">
    <label for="note-title">3</label>
    <input type="text" name="title" class="form-control" id="note-title" placeholder="Enter Title" required>
  </div>
    <div class="form-group">
    <label for="note-title">4</label>
    <input type="text" name="title" class="form-control" id="note-title" placeholder="Enter Title" required>
  </div>
    <div class="form-group">
    <label for="note-title">5</label>
    <input type="text" name="title" class="form-control" id="note-title" placeholder="Enter Title" required>
  </div>
  <div class="form-group">
    <label for="note-image">Images</label>
    <input type="file" name="images" class="form-control-file" id="note-image" multiple>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>


=======
<div style="margin-top: 5%; margin-left: 5%">
    <h3 style="color: #fff">Добавить метку</h3>

    <form method="post" enctype="multipart/form-data" class="post-form" style="margin-top: 10%">
        {% csrf_token %}
        {{ form.name }}<br>
        {{ form.description }}<br>
        {{ form.image }}<br>
        {{ form.location }}<br>

        <button type="submit" name="btnform1" class="btn btn-primary" style="margin-top: 5%">Добавить</button>
        {{ form.x_coord }}<br>
        {{ form.y_coord }}<br>
        {{ form.user }}<br>

    <script>$("#id_user").val({{ user.id }});</script>
    <script>$("#id_user").css("visibility", "hidden");</script>

    </form>
</div>
>>>>>>> Stashed changes